disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_cast
  - variable_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 200
  error: 300
