# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Honey4Groceries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Honey4Groceries
  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.7'
  pod 'PromiseKit/CorePromise', '~> 6.0'
  pod 'SwiftyJSON', '~> 4.0'

end
